POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "Admin123!"
}

###

DELETE  http://localhost:5000/logout
Content-Type: application/json
Cookie: refresh_token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxMzZjYzdjLTBiOGYtNGU0Mi05NTE2LTE2OTVlZDYyY2M2YSIsImlhdCI6MTcyOTAyOTk3MiwiZXhwIjoxNzMxNjIxOTcyfQ.k5uj56_n_rxUY1edQMEuHdcsGaqDlBAiIQW-HOfK_VS6c1z_5gDtALVbrnjt9wM2AdEWspxMaSva1XwbabJsuQ

###

POST http://localhost:5000/holiday/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxMzZjYzdjLTBiOGYtNGU0Mi05NTE2LTE2OTVlZDYyY2M2YSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMwNDkyMzU1LCJleHAiOjE3MzA0OTMyNTV9.s57kEBHXYHKfViU5tdLCyEhBxNCWp2iuW8YYkYQcBwe37Su5xaS7j0VMzK4A396hKiIuqtNB03Y-xL6DL0TAsQ

{
    "startDate": "2024-12-20",
    "endDate": "2024-12-20",
    "description": "test",
    "holidayType": "annual"
}

###

DELETE http://localhost:5000/holiday/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxMzZjYzdjLTBiOGYtNGU0Mi05NTE2LTE2OTVlZDYyY2M2YSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMwOTk1NDcxLCJleHAiOjE3MzA5OTYzNzF9.MpULliYWI5J2QZuy50romIGMgxohyQon9UZVCrO6r9zswUkASMsb1QJZVjoqS5O0RXTLdx36MaJGXsR-nWes_Q

{
    "holidayId": "31eb5d88-1297-4af1-bbcf-db70ab8880f1"
}

###

PUT  http://localhost:5000/holiday/accept
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxMzZjYzdjLTBiOGYtNGU0Mi05NTE2LTE2OTVlZDYyY2M2YSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMTA3NjU0NCwiZXhwIjoxNzMxMDc3NDQ0fQ.ZWNnN3ynHuCLSZR_R-3KaUgRtz1Qb5uE9wO2hNjk2I8TROEtj1hOHnGd4kxYsCG-daRDUilATAG5WCHCqlmvMw

{
    "holidayId": "0f8ad438-838d-4275-9ad3-bb7b2d578be1"
}

###

POST http://localhost:5000/token/refresh
Content-Type: application/json
Cookie: refresh_token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxMzZjYzdjLTBiOGYtNGU0Mi05NTE2LTE2OTVlZDYyY2M2YSIsImlhdCI6MTczMDQ5NDk3OSwiZXhwIjoxNzMzMDg2OTc5fQ.I9RGtGfi5h29D_QjBHZp0vM8ZPITc8MNrMtHOMhNB_1jUeFrILytsbjNyjEsH7c6Hasr-szvtziYKlldY8MpLg

###

POST http://localhost:5000/user/create
Content-Type: application/json

{
    "name": "admin",
    "surname": "admin",
    "email": "admin@admin.com",
    "password": "Admin123!"
}

###

GET http://localhost:5000/holiday/own
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1M2NhZjFmLTRlNzgtNDgxNi04ZjQ5LTI0MDU2MjFiMWNjMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMzcwMjUzMywiZXhwIjoxNzMzNzAzNDMzfQ.mbHz0iNft-PgHx48QEP_mQFNTW3n-igiZdYNtbYi9p8-DMkVl6ZUI1-2MIPOGV380w8x3EnGBJAzmXrBz2pzbA

###

GET http://localhost:5000/holiday/group
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1M2NhZjFmLTRlNzgtNDgxNi04ZjQ5LTI0MDU2MjFiMWNjMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMzcwMjUzMywiZXhwIjoxNzMzNzAzNDMzfQ.mbHz0iNft-PgHx48QEP_mQFNTW3n-igiZdYNtbYi9p8-DMkVl6ZUI1-2MIPOGV380w8x3EnGBJAzmXrBz2pzbA

###

GET http://localhost:5000/holiday/all
Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1M2NhZjFmLTRlNzgtNDgxNi04ZjQ5LTI0MDU2MjFiMWNjMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMzcxNDI4NCwiZXhwIjoxNzMzNzE1MTg0fQ.eKVAPJ3xu111_0iG31l79TEIygbNJDxJAHwGBcvHm9eJd-NvZVdU-hfza12X2S_8qdbLae7PcPnKj1Xc2zgDhQ

###

GET http://localhost:5000/holiday/employee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1M2NhZjFmLTRlNzgtNDgxNi04ZjQ5LTI0MDU2MjFiMWNjMiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMzcwMjUzMywiZXhwIjoxNzMzNzAzNDMzfQ.mbHz0iNft-PgHx48QEP_mQFNTW3n-igiZdYNtbYi9p8-DMkVl6ZUI1-2MIPOGV380w8x3EnGBJAzmXrBz2pzbA

{
    "employeeId": "8139da5e-8718-469e-a535-7ebc52bdbad2"
}

###

GET http://localhost:5000/user/data/own
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkNzZiYmNhLWI1MWUtNDllMS1hOGYwLWI1NzZjZjAxYWZlYiIsInJvbGUiOiJodW1hbl9yZXNvdXJjZXMiLCJpYXQiOjE3MzQyOTI2MTcsImV4cCI6MTczNDI5MzUxN30.dKEeTfUqaA7OzRI7iA1amR0y9hDjbQYp3UuATZiSL4KngBKAMbqiizogcFLpzGBhiOxiwf-9oWBxy2f3WWD3Sw

###

GET http://localhost:5000/user/data/employee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkNzZiYmNhLWI1MWUtNDllMS1hOGYwLWI1NzZjZjAxYWZlYiIsInJvbGUiOiJodW1hbl9yZXNvdXJjZXMiLCJpYXQiOjE3MzQyOTI2MTcsImV4cCI6MTczNDI5MzUxN30.dKEeTfUqaA7OzRI7iA1amR0y9hDjbQYp3UuATZiSL4KngBKAMbqiizogcFLpzGBhiOxiwf-9oWBxy2f3WWD3Sw

{
    "employeeId": "3874b1ed-345b-419f-8623-be7f5bec5a20"
}

###

POST http://localhost:5000/group/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4ZDdlODc0LWQyMmYtNGFmMi1iM2FhLWZmY2M2NjgwMzA0YyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDM2MzUyMywiZXhwIjoxNzM0MzY0NDIzfQ.0MY1xUa-8mm5x0Z0ihy7OEN2lZmTUfNFHVv4eaBhjXObXWZ0JXzbeArLytzqJ5Wvpfnp8hUhm_d-dyQ0q4VCMg

{
    "name": "Kadry",
    "leaderId": "e911221b-c61b-4633-95ea-02f394dcc94c"
}

###