POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "Admin123!"
}

###

DELETE  http://localhost:5000/logout
Content-Type: application/json
Cookie: refresh_token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxMzZjYzdjLTBiOGYtNGU0Mi05NTE2LTE2OTVlZDYyY2M2YSIsImlhdCI6MTcyOTAyOTk3MiwiZXhwIjoxNzMxNjIxOTcyfQ.k5uj56_n_rxUY1edQMEuHdcsGaqDlBAiIQW-HOfK_VS6c1z_5gDtALVbrnjt9wM2AdEWspxMaSva1XwbabJsuQ

###

POST http://localhost:5000/holiday/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxMzZjYzdjLTBiOGYtNGU0Mi05NTE2LTE2OTVlZDYyY2M2YSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMwNDc4MTg3LCJleHAiOjE3MzA0NzkwODd9.G-fRZOoauyid3QU1-TNUG5L_ZNyMkrBTpHjmcIYmSyECz8OL1LUPxvQ5bHA-8UiZwJaxKgTVn_SItkDLrmr8JA

{
    "startDate": "2024-12-18",
    "endDate": "2024-12-18",
    "desciption": "test",
    "holidayType": "annual"
}

###

POST http://localhost:5000/token/refresh
Content-Type: application/json
Cookie: refresh_token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxMzZjYzdjLTBiOGYtNGU0Mi05NTE2LTE2OTVlZDYyY2M2YSIsImlhdCI6MTcyOTAyOTk3MiwiZXhwIjoxNzMxNjIxOTcyfQ.k5uj56_n_rxUY1edQMEuHdcsGaqDlBAiIQW-HOfK_VS6c1z_5gDtALVbrnjt9wM2AdEWspxMaSva1XwbabJsuQ

###

POST http://localhost:5000/user/create
Content-Type: application/json

{
    "name": "admin",
    "surname": "admin",
    "email": "admin@admin.com",
    "password": "Admin123!"
}
